### ISSUE TITLE
Exit on SIGINT

### ISSUE THREAD

**Issue by james-callahan** [tkhq/ecr-proxy#1]
Currently pressing Ctrl+c doesn't exit ecr-proxy.
Add some sort of SIGINT handling to exit when Ctrl+c is pressed.

**Comment by james-callahan** [comment]
@Ulexus I think this was fixed via 0ecce6b82b0312f4bb69264f3960a06733f28733?

**Comment by Ulexus** [comment]
Yep, should have been.  I didn't know this issue existed
